(*Generated by Lem from abis/riscv/abi_riscv_program_header_table.lem.*)
(** [abi_riscv_program_header_table], program header table specific definitions
  * for the RISCV ABI.
  *)

open Lem_basic_classes
open Lem_bool
open Lem_num
open Lem_string

(** New segment types. *)

(** [string_of_abi_riscv_elf_segment_type m] produces a string based representation
  * of RISCV segment type [m].
  *)
(*val string_of_abi_riscv_elf_segment_type : natural -> string*)
let string_of_abi_riscv_elf_segment_type m:string=
     "Invalid RISCV segment type"

(** [abi_riscv_is_valid_program_interpreter s] checks whether the program interpreter
  * string is valid for RISCV ABI.
  * See Section XXX FIXME
  *)
(*val abi_riscv_is_valid_program_interpreter : string -> bool*)
let abi_riscv_is_valid_program_interpreter s:bool=
   (s = "/lib/ld64.so.1")
