(*Generated by Lem from abis/riscv/abi_riscv_serialisation.lem.*)
(** [abi_riscv_serialisation] contains code for producing an RISCV conformant
  * ELF file from executable (machine) code.
  * Used in ongoing experiments with CakeML.
  *
  * XXX: experimental, and outdated.  Commented out for now until attention turns
  * to CakeML again.
  *)

open Lem_basic_classes
open Lem_list
open Lem_maybe
open Lem_num

open Byte_sequence
open Missing_pervasives

open Memory_image
open Elf_file
open Elf_header
open Elf_interpreted_segment
open Elf_program_header_table
open Elf_section_header_table
open Elf_types_native_uint

open Abi_riscv_elf_header

