(*Generated by Lem from abis/riscv/abi_riscv_relocation.lem.*)
(** [abi_riscv_relocation] contains types and definitions relating to ABI
  * specific relocation functionality for the RISCV ABI.
  *)

open Lem_basic_classes
open Lem_map
open Lem_maybe
open Lem_num
open Lem_string

open Error
open Missing_pervasives
open Lem_assert_extra

open Elf_types_native_uint
open Elf_file
open Elf_header
open Elf_relocation
open Elf_symbol_table
open Memory_image

open Abi_classes
open Abi_utilities

(* FIXME: this file *)
