(*Generated by Lem from abis/cheri_mips64/abi_cheri_mips64.lem.*)
open Lem_basic_classes
open Lem_bool
open Lem_maybe
open Lem_string

open Elf_types_native_uint
open Abi_cheri_mips64_elf_header
open Elf_header
open Missing_pervasives
open Show

(*val header_is_cheri_mips64 : elf64_header -> bool*)
let header_is_cheri_mips64 h:bool=
   (is_valid_elf64_header h
    && ((Lem.option_equal (=) (Lem_list.list_index h.elf64_ident (Nat_big_num.to_int elf_ii_data)) (Some (Uint32_wrapper.of_bigint abi_cheri_mips64_data_encoding)))
    && (is_valid_abi_cheri_mips64_machine_architecture (Uint32_wrapper.to_bigint h.elf64_machine)
    && (is_valid_abi_cheri_mips64_magic_number h.elf64_ident
    && is_valid_abi_cheri256_mips64_flag (Uint32_wrapper.to_bigint h.elf64_flags)))))

(*val header_is_pure_cheri_mips64 : elf64_header -> bool*)
let header_is_pure_cheri_mips64 h:bool=
   (header_is_cheri_mips64 h
    && is_pure_abi_cheri_mips64_flag (Uint32_wrapper.to_bigint h.elf64_flags))
