(*Generated by Lem from filesystem.lem.*)
open Error

(*val dirname : string -> string*)

(*val normalize : string -> string*)

(*val to_absolute : string -> string -> string*)

(*val readlink : string -> error (string)*)

(*val realpath_in : string -> string -> error (string)*)

(*val realpath : string -> error (string)*)

(*val readdir : string -> error (list string)*)

(*val file_exists : string -> bool*)
